DROP TABLE IF EXISTS books;

CREATE TABLE books(
ID INT AUTO_INCREMENT PRIMARY KEY,
AUTHOR_ID VARCHAR(250) NOT NULL,
TITLE VARCHAR(250) NOT NULL,
PRICE_OLD VARCHAR(250) DEFAULT NULL,
PRICE VARCHAR(250) DEFAULT NULL
);